### ISSUE TITLE
Characters not shown

### ISSUE THREAD

**Issue by MarcoSteinke** [P3N9U1N/diablo2-savegames#2]
Hey I downloaded the characters and placed them in my d2 directory. But they are not displayed. Are they in the wrong format, or do I have to do something to make them visible?

**Comment by P3N9U1N** [comment]
Hey,
Diablo 2 has a dedicated save directory, you need to place the files there. The location of the save file directory depends on the Diablo 2 version you are using, see here: https://www.reddit.com/r/Diablo/comments/a26us8/where_are_the_save_files_located_for_diablo_2/
________________________________
Von: Marco Steinke ***@***.***>
Gesendet: Freitag, 13. September 2024 12:05
An: P3N9U1N/diablo2-savegames ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [P3N9U1N/diablo2-savegames] Characters not shown (Issue #2)


Hey I downloaded the characters and placed them in my d2 directory. But they are not displayed. Are they in the wrong format, or do I have to do something to make them visible?

**Comment by MarcoSteinke** [comment]
Thank you for the response :) I totally forgot about this :)
